[build]
  publish = "frontend"

# Pass API requests directly to the deployed backend server if using proxy
[[redirects]]
  from = "/api/*"
  to = "https://YOUR-BACKEND-URL.onrender.com/api/:splat"
  status = 200
